#ifndef INPUT_KEYCODE_HPP
#define INPUT_KEYCODE_HPP

#include <array>
#include <cstdint>
#include <utility>

#include "input/scancode.hpp"

enum class KeyCode : uint32_t {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    N0,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,

    BackTick,
    Minus,
    Equals,
    BackSlash,
    BackSpace,

    Space,
    Tab,
    CapsLock,

    LeftShift,
    RightShift,
    LeftControl,
    LeftAlt,
    Enter,
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,

    LeftBracket,
    RightBracket,
    SemiColon,
    Quote,
    Comma,
    Period,
    Slash,
};

inline std::array<std::pair<KeyCode, Keyboard::ScanCode>, 69> default_mapping {{
    { KeyCode::A, Keyboard::A },
    { KeyCode::B, Keyboard::B },
    { KeyCode::C, Keyboard::C },
    { KeyCode::D, Keyboard::D },
    { KeyCode::E, Keyboard::E },
    { KeyCode::F, Keyboard::F },
    { KeyCode::G, Keyboard::G },
    { KeyCode::H, Keyboard::H },
    { KeyCode::I, Keyboard::I },
    { KeyCode::J, Keyboard::J },
    { KeyCode::K, Keyboard::K },
    { KeyCode::L, Keyboard::L },
    { KeyCode::M, Keyboard::M },
    { KeyCode::N, Keyboard::N },
    { KeyCode::O, Keyboard::O },
    { KeyCode::P, Keyboard::P },
    { KeyCode::Q, Keyboard::Q },
    { KeyCode::R, Keyboard::R },
    { KeyCode::S, Keyboard::S },
    { KeyCode::T, Keyboard::T },
    { KeyCode::U, Keyboard::U },
    { KeyCode::V, Keyboard::V },
    { KeyCode::W, Keyboard::W },
    { KeyCode::X, Keyboard::X },
    { KeyCode::Y, Keyboard::Y },
    { KeyCode::Z, Keyboard::Z },

    { KeyCode::N0, Keyboard::N0 },
    { KeyCode::N1, Keyboard::N1 },
    { KeyCode::N2, Keyboard::N2 },
    { KeyCode::N3, Keyboard::N3 },
    { KeyCode::N4, Keyboard::N4 },
    { KeyCode::N5, Keyboard::N5 },
    { KeyCode::N6, Keyboard::N6 },
    { KeyCode::N7, Keyboard::N7 },
    { KeyCode::N8, Keyboard::N8 },
    { KeyCode::N9, Keyboard::N9 },

    { KeyCode::BackTick,  Keyboard::BackTick },
    { KeyCode::Minus,     Keyboard::Minus },
    { KeyCode::Equals,    Keyboard::Equals },
    { KeyCode::BackSlash, Keyboard::BackSlash },
    { KeyCode::BackSpace, Keyboard::BackSpace },

    { KeyCode::Space,    Keyboard::Space },
    { KeyCode::Tab,      Keyboard::Tab },
    { KeyCode::CapsLock, Keyboard::CapsLock },

    { KeyCode::LeftShift,   Keyboard::LeftShift },
    { KeyCode::RightShift,  Keyboard::RightShift },
    { KeyCode::LeftControl, Keyboard::LeftControl },
    { KeyCode::LeftAlt,     Keyboard::LeftAlt },
    { KeyCode::Enter,       Keyboard::Enter },
    { KeyCode::Escape,      Keyboard::Escape },

    { KeyCode::F1,  Keyboard::F1 },
    { KeyCode::F2,  Keyboard::F2 },
    { KeyCode::F3,  Keyboard::F3 },
    { KeyCode::F4,  Keyboard::F4 },
    { KeyCode::F5,  Keyboard::F5 },
    { KeyCode::F6,  Keyboard::F6 },
    { KeyCode::F7,  Keyboard::F7 },
    { KeyCode::F8,  Keyboard::F8 },
    { KeyCode::F9,  Keyboard::F9 },
    { KeyCode::F10, Keyboard::F10 },
    { KeyCode::F11, Keyboard::F11 },
    { KeyCode::F12, Keyboard::F12 },

    { KeyCode::LeftBracket,  Keyboard::LeftBracket },
    { KeyCode::RightBracket, Keyboard::RightBracket },
    { KeyCode::SemiColon,    Keyboard::SemiColon },
    { KeyCode::Quote,        Keyboard::Quote },
    { KeyCode::Comma,        Keyboard::Comma },
    { KeyCode::Period,       Keyboard::Period },
    { KeyCode::Slash,        Keyboard::Slash }
}};

KeyCode get_keycode(const ScanCode& scancode);

#endif
